version: "3.9"
services:
  database:
    image: postgres
    container_name: szarnapomvan-db
    environment:
      POSTGRES_USER: szarnapomvan
      POSTGRES_PASSWORD: szarnapomvan
      POSTGRES_DB: szarnapomvan
    ports:
      - 5435:5432
    volumes:
      - szarnapomvan_db_data:/var/lib/postgresql/data
    networks:
      - szarnapomvan_network

volumes:
  szarnapomvan_db_data:

networks:
  szarnapomvan_network:
    driver:
      bridge